services:

  db:
    image: postgres:18
    container_name: chatgpt-clone-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: chatgpt-clone-app
    restart: unless-stopped

    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: ${APP_ENV}
      DEBUG: ${DEBUG}

      GROQ_API_KEY: ${GROQ_API_KEY}
      GROQ_MODEL: ${GROQ_MODEL}

      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      TEST_DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}

      CHAT_CONTEXT_TOKEN_BUDGET: ${CHAT_CONTEXT_TOKEN_BUDGET}
      CHAT_SYSTEM_PROMPT: ${CHAT_SYSTEM_PROMPT}
      CHAT_MAX_OUTPUT_TOKENS: ${CHAT_MAX_OUTPUT_TOKENS}

    ports:
      - "8000:8000"

    depends_on:
      db:
        condition: service_healthy


volumes:
  postgres_data:
